### ISSUE TITLE
Cameras behave weirdly on certain transitions (gets fixed by retrying)

### ISSUE THREAD

**Issue by UltraMarlin** [rhelmot/CelesteRandomizer#53]
This can cause the camera to put you off screen, which can be a forced death like in this situation: https://discordapp.com/channels/403698615446536203/738558439227392082/739498574710046800

But also just looks weird in other cases. Had it happen once on a transition from a badeline orb throw into 4A a-09 where the camera was slightly too far left, making the right side wall not visible (but still useable).

Another case of this happening was transitioning from a farewell screen (forgot which one, mightve been e-05) to 6B c-02, where the camera was a lot lower than its supposed to be.

**Comment by UltraMarlin** [comment]
Seems like this happens usually when exiting a badeline orb transition. For some reason the camera gets stuck in one place

**Comment by rhelmot** [comment]
This one really has me stumped. I've spent like two hours pouring over the disassembly and searching for seeds which exhibit behavior, and I only found one seed with pathological camera behavior. The map was laid out as follows; the big 04 room from from 6a was connected at its bottom right exit to 7b e-03. Whenever you spawned yourself at either of the upper entrances of 04, entering e-03 would result in a camera shifted upwards until you retry. From what I can tell, no camera triggers in the former room had any affect on the result, and once you'd retried in e-03, some state was set which actually prevented you from triggering the bug again - traversing upwards to the top entrances, re-entering and exiting, and then going back to e-03 would not give you a bad camera.

I really don't know how to go forward with debugging this. Maybe someone with a lot of domain knowledge on how celeste's camera system works could be tapped for help?

**Comment by SuperSupermario24** [comment]
In the case of the video Marlin linked in the first post, it's definitely caused by the Badeline orb. It adds a camera locker that locks the camera vertically, depending on how far up the camera has moved. The trouble is, the camera lock doesn't reset properly across screen transitions. You can actually get this effect in vanilla Summit - search for "camera lock" in `#bug_reports` for a video.

I'm guessing the reason you were having trouble reproducing it is because it probably requires going through most of the level without dying, since (AFAIK) it _does_ properly reset itself on death and debug respawning. Essentially, you have to manage to scroll the camera up pretty far relative to the room, then transition into the room, all without dying.

To be more specific, the culprit here seems to be in `Level.LoadLevel` (the `orig_` version, if you're looking at the code with Everest patches). The value that determines the camera lock `Level.CameraUpwardMaxY`, and this is reset to its default value during level loading - _except_ for when `playerIntro` is 0, which is the Transition state, so it won't reset itself during screen transitions.

As for the issue in 6B - I'm quite certain that's also caused by camera locking, since c-02 is a Badeline boss room, which locks the camera in a similar way, but the way it determines where to lock the camera seems less certain to me.

**Comment by rhelmot** [comment]
I talked with SSM a bit offline and we figured out a really simple fix for the first flavor of the issue, where entering badeline rooms can kill you. See linked commit. I'll leave this issue open until I can reproduce and track down the other flavor of issue.

**Comment by rhelmot** [comment]
I FIGURED IT OUT

this is a bug specific to the last room of 500m because the camera target trigger that keeps you from seeing the berry actually had a y-position of -8, so it was still taken into account while figuring out the camera positioning for the next level. However, it is then unloaded before madeline ever properly leaves the trigger area, so the OnLeave handler is never triggered so the level is perpetually stuck in the locked-to-the-left-side-of-the-screen mode. The fix is just moving the trigger down 8 pixels.
